import type { Product, Order, Address, GuildMember } from '../types'
import { slugify } from './slugify'

// images field is required by the Product type; mockData uses empty arrays since
// real images come from Supabase Storage (image_urls column).
export const PRODUCTS: Product[] = [
  {
    id: '1',
    slug: slugify('Catan: El Juego Base'),
    name: 'Catan: El Juego Base',
    price: 45.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5ltB0UDv5UXnON9w5Yd_MO3kSPgGuTSVa22iNSBHpyFrZP4mxn_g3Bw3xiuxU0LpGJEHK820qzU-IykfVs6PHfM0z5i-rhmar5tZqKu04DF3LwtkZwfreDiWEGoAVIWW8PRE6k0yOjHjct7jz50oyiNSY3wkv8hTMf26_0PJBl2pyXXfYsJwPFgap2RImAJrbPpBuxZZfxa3TDZxNS6MmrwHlb4nCneCi5GAdCBKXXEpp5iWbj37FqnZIh58BPQ9SlXqP3xsk3zc3',
    images: [],
    category: 'base',
    badge: 'Juego Base',
    description: 'El juego de estrategia definitivo. Coloniza la isla de Catan, comercia recursos y construye el mayor imperio.',
    stock: 15,
    rating: 4.9,
    reviews: 248,
  },
  {
    id: '2',
    slug: slugify('Catan: Navegantes'),
    name: 'Catan: Navegantes',
    price: 39.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyfFRmM2rVewc2EtjVGWRavPXwTikEhxkqOGw_fC_9WzoJZs81T6iTkE-P0238I8tQk-cw4WH__qK8Gd13HFpOaXH4DElMDVojHkLA2YW93hCIF8Zlj0HpEYW9A3WximnY2rTYFSQdPox5oyDp27_12pazrR625IRQSnpfnQgZjrv3ccfZbMs9fcXS1EcpkxIKNvyLDRc--y32AYPHWrWEPIZSpE1EnAdtgp0SpMgdmJDIE1_ONWnehYntiC6YyvSX91ZpHz3gZaUf',
    images: [],
    category: 'expansion',
    badge: 'Expansión',
    description: 'Explora los mares. Descubre nuevas islas y comercia a través de los océanos.',
    stock: 8,
    rating: 4.7,
    reviews: 132,
  },
  {
    id: '3',
    slug: slugify('Catan: Ciudades y Caballeros'),
    name: 'Catan: Ciudades y Caballeros',
    price: 42.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBPh0sLP-W4xpuTE14v70717E_jEs7y6l9xumGtaAi9BpQq7leUaQcqPuXH3T4n4MpY2aRAes0vqpkHXATMY0pb_FB5u0CxCKu6O1ABOeNBoT-u5EmjZ05PZe10f3wpurEvTVnm6Dm75ix6tzNYw65jSxZD3kQmVEYOd6Zob0hhDrGh-120s7k3OpC9tY1cPf84WfPesyH-G2GOwkizT1Hd8AVxxQ-PvRgU-3obcdm8deDcN_2iLSh0bKzt9vQVGgTtqPJzMxqTl9JW',
    images: [],
    category: 'expansion',
    badge: 'Expansión',
    description: 'Desarrolla ciudades y entrena caballeros para proteger tus tierras de los bárbaros.',
    stock: 12,
    rating: 4.8,
    reviews: 189,
  },
  {
    id: '4',
    slug: slugify('Catan: Ampliación 5-6 Jugadores'),
    name: 'Catan: Ampliación 5-6 Jugadores',
    price: 25.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClO-03JocHr-8uaq6esAaSc5XLyjztStYWMNBb4KUtYp_DvPk9SlXqP3xsk3zc3',
    images: [],
    category: 'expansion',
    description: 'Juega con hasta 6 jugadores. Compatible con el juego base.',
    stock: 20,
    rating: 4.5,
    reviews: 98,
  },
  {
    id: '5',
    slug: slugify('Catan: Comerciantes y Bárbaros'),
    name: 'Catan: Comerciantes y Bárbaros',
    price: 38.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD5ltB0UDv5UXnON9w5Yd_MO3kSPgGuTSVa22iNSBHpyFrZP4mxn_g3Bw3xiuxU0LpGJEHK820qzU-IykfVs6PHfM0z5i-rhmar5tZqKu04DF3LwtkZwfreDiWEGoAVIWW8PRE6k0yOjHjct7jz50oyiNSY3wkv8hTMf26_0PJBl2pyXXfYsJwPFgap2RImAJrbPpBuxZZfxa3TDZxNS6MmrwHlb4nCneCi5GAdCBKXXEpp5iWbj37FqnZIh58BPQ9SlXqP3xsk3zc3',
    images: [],
    category: 'expansion',
    badge: 'Expansión',
    description: 'Cinco nuevos escenarios que enriquecen la experiencia de Catan.',
    stock: 6,
    rating: 4.6,
    reviews: 74,
  },
  {
    id: '6',
    slug: slugify('Set de Dados Premium Catan'),
    name: 'Set de Dados Premium Catan',
    price: 18.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBPh0sLP-W4xpuTE14v70717E_jEs7y6l9xumGtaAi9BpQq7leUaQcqPuXH3T4n4MpY2aRAes0vqpkHXATMY0pb_FB5u0CxCKu6O1ABOeNBoT-u5EmjZ05PZe10f3wpurEvTVnm6Dm75ix6tzNYw65jSxZD3kQmVEYOd6Zob0hhDrGh-120s7k3OpC9tY1cPf84WfPesyH-G2GOwkizT1Hd8AVxxQ-PvRgU-3obcdm8deDcN_2iLSh0bKzt9vQVGgTtqPJzMxqTl9JW',
    images: [],
    category: 'accessory',
    badge: 'Accesorio',
    description: 'Dados de madera con iconos temáticos de Catan. Calidad premium.',
    stock: 30,
    rating: 4.4,
    reviews: 56,
  },
  {
    id: '7',
    slug: slugify('Catan: El Juego de Cartas'),
    name: 'Catan: El Juego de Cartas',
    price: 22.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyfFRmM2rVewc2EtjVGWRavPXwTikEhxkqOGw_fC_9WzoJZs81T6iTkE-P0238I8tQk-cw4WH__qK8Gd13HFpOaXH4DElMDVojHkLA2YW93hCIF8Zlj0HpEYW9A3WximnY2rTYFSQdPox5oyDp27_12pazrR625IRQSnpfnQgZjrv3ccfZbMs9fcXS1EcpkxIKNvyLDRc--y32AYPHWrWEPIZSpE1EnAdtgp0SpMgdmJDIE1_ONWnehYntiC6YyvSX91ZpHz3gZaUf',
    images: [],
    category: 'base',
    description: 'La versión de dos jugadores del clásico Catan. Perfecta para parejas.',
    stock: 9,
    rating: 4.3,
    reviews: 45,
  },
  {
    id: '8',
    slug: slugify('Organizador de Madera para Catan'),
    name: 'Organizador de Madera para Catan',
    price: 55.0,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuClO-03JocHr-8uaq6esAaSc5XLyjztStYWMNBb4KUtYp_DvPk9SlXqP3xsk3zc3',
    images: [],
    category: 'accessory',
    badge: 'Accesorio',
    description: 'Organizador artesanal de madera. Guarda perfectamente el juego base y expansiones.',
    stock: 4,
    rating: 4.9,
    reviews: 33,
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-2024-001',
    userId: '2',
    items: [{ product: PRODUCTS[0], quantity: 1 }, { product: PRODUCTS[1], quantity: 1 }],
    total: 84.0,
    status: 'delivered',
    createdAt: '2024-11-15',
    paymentMethod: 'Mercado Pago',
  },
  {
    id: 'ORD-2024-002',
    userId: '2',
    items: [{ product: PRODUCTS[2], quantity: 1 }],
    total: 42.0,
    status: 'shipped',
    createdAt: '2024-12-01',
    paymentMethod: 'Mercado Pago',
  },
  {
    id: 'ORD-2024-003',
    userId: '2',
    items: [{ product: PRODUCTS[5], quantity: 2 }],
    total: 36.0,
    status: 'pending',
    createdAt: '2024-12-10',
    paymentMethod: 'Mercado Pago',
  },
]

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    label: 'Casa',
    street: 'Av. Corrientes 1234, Piso 3 Dpto B',
    city: 'Buenos Aires',
    province: 'CABA',
    postalCode: 'C1043',
    isDefault: true,
  },
  {
    id: 'addr-2',
    label: 'Trabajo',
    street: 'Av. del Libertador 5678',
    city: 'Buenos Aires',
    province: 'CABA',
    postalCode: 'C1426',
    isDefault: false,
  },
]

export const GUILD_MEMBERS: GuildMember[] = [
  { id: '1', name: 'Admin', email: 'admin@elmercader.com', role: 'admin', guild: 'Maestros del Trigo', joinedAt: '2023-01-01', totalOrders: 0, totalSpent: 0 },
  { id: '2', name: 'Juan García', email: 'juan@email.com', role: 'user', guild: 'Navegantes', joinedAt: '2024-01-15', totalOrders: 12, totalSpent: 580 },
  { id: '3', name: 'María López', email: 'maria@email.com', role: 'user', guild: 'Mineros', joinedAt: '2024-02-20', totalOrders: 8, totalSpent: 342 },
  { id: '4', name: 'Carlos Ruiz', email: 'carlos@email.com', role: 'user', guild: 'Leñadores', joinedAt: '2024-03-10', totalOrders: 5, totalSpent: 215 },
  { id: '5', name: 'Ana Martínez', email: 'ana@email.com', role: 'user', joinedAt: '2024-04-05', totalOrders: 3, totalSpent: 127 },
]
