/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#812e19',
        'primary-container': '#a0452e',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a2',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffd3c8',
        'on-primary-fixed': '#3c0700',
        'on-primary-fixed-variant': '#7e2c17',
        'inverse-primary': '#ffb4a2',
        secondary: '#3b6934',
        'secondary-container': '#b9eeab',
        'secondary-fixed': '#bcf0ae',
        'secondary-fixed-dim': '#a1d494',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#3f6d38',
        'on-secondary-fixed': '#002201',
        'on-secondary-fixed-variant': '#23501e',
        tertiary: '#735c00',
        'tertiary-container': '#cba72f',
        'tertiary-fixed': '#ffe088',
        'tertiary-fixed-dim': '#e9c349',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#4e3d00',
        'on-tertiary-fixed': '#241a00',
        'on-tertiary-fixed-variant': '#574500',
        background: '#fff9eb',
        'on-background': '#1d1c13',
        surface: '#fff9eb',
        'surface-bright': '#fff9eb',
        'surface-dim': '#dfdacc',
        'surface-variant': '#e8e2d4',
        'surface-tint': '#9d422c',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f9f3e5',
        'surface-container': '#f3eddf',
        'surface-container-high': '#eee8da',
        'surface-container-highest': '#e8e2d4',
        'on-surface': '#1d1c13',
        'on-surface-variant': '#56423e',
        'inverse-surface': '#333027',
        'inverse-on-surface': '#f6f0e2',
        outline: '#89726c',
        'outline-variant': '#dcc1ba',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['"Libre Caslon Text"', 'serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        gutter: '24px',
        'container-max': '1280px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
